# DB setting
spring:
  datasource:
#    url: jdbc:mysql://192.168.100.49:3306/pj1984?useUnicode=true&characterEncoding=UTF-8&characterSetResult=UTF-8&useSSL=true
    url: jdbc:mysql://localhost:3306/pj1984?useUnicode=true&characterEncoding=UTF-8&characterSetResult=UTF-8&useSSL=true
#    username: root
    username: pj1984
#    password: 1234
    password: pj1984!!
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true


logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.orm.jdbc.bind: trace

server:
  port: 8083
  servlet:
    encoding:
      force-response: true
      charset: UTF-8
    session:
      tracking-modes: cookie

iamport:
  key: 1438164817253007
  secret: BIbJ0zJL1smO9Kdbjmmf7epKUC6F0sM1swDVgzjfpJdwYXugBcgAjhE7LGZ976K14ZxK9tVY2cZx1PRv

file:
  dir: C:/pj1984/images/
#  dir: C:/lhw/images/
#  dir: /Users/hoseonyoo/Documents/file/
#  dir: C:\thejoeun\dataCollection\
#  dir: C:\HJ\pj1984\
